export const getBlogs = async () => {
  return [
    {
      thumbImage: '/images/blog/blog-md-1.png',
      writter: 'John Smith',
      date: 'November 16, 2022',
      title: 'Sollicitudin urna metus iaculis odio eget efficitur leo.',
      comments: '250',
    },
    {
      thumbImage: '/images/blog/blog-md-2.png',
      writter: 'John Smith',
      date: 'November 17, 2022',
      title: 'Variustempor convallis, mi ligula an suscipit nunc.',
      comments: '3',
    },
    {
      thumbImage: '/images/blog/blog-md-3.png',
      writter: 'John Smith',
      date: 'November 17, 2022',
      title: 'Aenean auctor porta sodales. Suspendisse fringilla neque.',
      comments: '2',
    },
    {
      thumbImage: '/images/blog/blog-md-4.png',
      writter: 'John Smith',
      date: 'November 17, 2022',
      title: 'Sollicitudin urna metus iaculis odio eget efficitur leo.',
      comments: '67',
    },
    {
      thumbImage: '/images/blog/blog-md-5.png',
      writter: 'John Smith',
      date: 'November 17, 2022',
      title: 'Variustempor convallis, mi ligula an suscipit nunc.',
      comments: '2',
    },
    {
      thumbImage: '/images/blog/blog-md-6.png',
      writter: 'John Smith',
      date: 'November 17, 2022',
      title: 'Nulla urna leo, volutpat eu maurisa eget luctus.',
      comments: '1',
    },
    {
      thumbImage: '/images/blog/blog-md-7.png',
      writter: 'John Smith',
      date: 'November 17, 2022',
      title: 'Duis pretium sit amet nisi a malesuada fusce congue.',
      comments: '127',
    },
    {
      thumbImage: '/images/blog/blog-md-8.png',
      writter: 'John Smith',
      date: 'November 17, 2022',
      title: 'Nam efficitur facilisis tinciduntent curabitur vitae.',
      comments: '27',
    },
    {
      thumbImage: '/images/blog/blog-md-9.png',
      writter: 'John Smith',
      date: 'November 17, 2022',
      title: 'Variustempor convallis, mi ligula an suscipit nunc.',
      comments: '55',
    },
    {
      thumbImage: '/images/blog/blog-md-10.png',
      writter: 'John Smith',
      date: 'November 17, 2022',
      title: 'Nullam tristique laoreet tortor, in interdum elit.',
      comments: '12',
    },
    {
      thumbImage: '/images/blog/blog-md-11.png',
      writter: 'John Smith',
      date: 'November 17, 2022',
      title: 'Mauris commodo massa vel diamnat feugiat sagittis Nunc.',
      comments: '100',
    },
    {
      thumbImage: '/images/blog/blog-md-12.png',
      writter: 'Jane Doe',
      date: 'November 20, 2022',
      title: 'Fusce tristique placerat arcu, eget interdum lacus.',
      comments: '0',
    },
  ];
};
